import { Amplify } from 'aws-amplify';
import {
  signUp, confirmSignUp, signIn, signOut, getCurrentUser,
  resetPassword, confirmResetPassword, deleteUser
} from 'aws-amplify/auth';
import { generateClient } from 'aws-amplify/data';
import outputs from '../amplify_outputs.json'; // generated by `npx ampx sandbox` or a real deploy

Amplify.configure(outputs);
const client = generateClient();

/* ================= CONSTANTS ================= */
const ICONS = {
  dashboard: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="9"/><rect x="14" y="3" width="7" height="5"/><rect x="14" y="12" width="7" height="9"/><rect x="3" y="16" width="7" height="5"/></svg>',
  properties: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 10l9-7 9 7v9a2 2 0 01-2 2H5a2 2 0 01-2-2z"/></svg>',
  tenants: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-6 8-6s8 2 8 6"/></svg>',
  maintenance: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14.7 6.3a4 4 0 00-5.4 5.4L3 18v3h3l6.3-6.3a4 4 0 005.4-5.4l-2.8 2.8-2-2z"/></svg>',
  map: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 20l-6-3V4l6 3 6-3 6 3v13l-6-3-6 3z"/><path d="M9 4v13M15 7v13"/></svg>',
  contacts: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="4" y="2" width="16" height="20" rx="2"/><path d="M9 8h6M9 12h6M9 16h3"/></svg>',
  notes: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/></svg>'
};
const PAGES = [
  ['dashboard','Dashboard'],['properties','Properties'],['tenants','Tenants'],
  ['maintenance','Maintenance'],['map','Map'],['contacts','Contacts'],['notes','Upcoming Plans']
];
const CONTACT_TYPES = ['Plumber','Electrician','Carpenter','Painter','Pest Control','AC Repair','Mason','Other'];
const CURRENCIES = {
  INR: {symbol:'₹', locale:'en-IN', label:'INR — Indian Rupee'},
  USD: {symbol:'$', locale:'en-US', label:'USD — US Dollar'},
  EUR: {symbol:'€', locale:'en-GB', label:'EUR — Euro'},
  GBP: {symbol:'£', locale:'en-GB', label:'GBP — British Pound'},
  AED: {symbol:'AED ', locale:'en-AE', label:'AED — UAE Dirham'},
  AUD: {symbol:'A$', locale:'en-AU', label:'AUD — Australian Dollar'},
  CAD: {symbol:'C$', locale:'en-CA', label:'CAD — Canadian Dollar'},
  SGD: {symbol:'S$', locale:'en-SG', label:'SGD — Singapore Dollar'}
};

/* ================= STATE ================= */
let currentUser = null;
let cache = { properties: [], income: [], expenses: [], contacts: [], notes: [], settings: { appName: 'Rent Ledger', currency: 'INR' } };
let page = 'dashboard';
let authScreen = 'signin';
let pendingConfirmEmail = null;
let forgotEmail = null;
let leafletMap = null;
let chartInstance = null;
let maintenanceFilterId = 'all';

const uid = () => Math.random().toString(36).slice(2,10);
function money(n){
  const cur = CURRENCIES[cache.settings.currency || 'INR'];
  return cur.symbol + Number(n||0).toLocaleString(cur.locale, {maximumFractionDigits:0});
}
const thisMonth = () => new Date().toISOString().slice(0,7);
const today = () => new Date().toISOString().slice(0,10);
const monthLabel = ym => { const [y,m]=ym.split('-'); return new Date(y,m-1).toLocaleString('default',{month:'short'})+" '"+y.slice(2); };
function propName(id){ const p = cache.properties.find(p=>p.id===id); return p ? p.name : '—'; }
function propContacts(propertyId){ return cache.contacts.filter(c=>c.propertyId===propertyId); }

function withLoading(btn, fn){
  if(!btn || btn.dataset.busy) return;
  btn.dataset.busy = '1';
  const orig = btn.textContent;
  btn.disabled = true;
  btn.textContent = 'Saving…';
  Promise.resolve().then(fn).catch(e=>{ console.error(e); alert(e.message || 'Something went wrong — please try again.'); })
    .finally(()=>{ try{ btn.disabled = false; btn.textContent = orig; delete btn.dataset.busy; }catch(e){} });
}
function closeModal(){ document.querySelectorAll('.overlay').forEach(m=>m.remove()); }

/* ================= DATA LAYER (Amplify Data / DynamoDB) ================= */
async function refreshCache(){
  const [props, income, expenses, contacts, notes, settingsList] = await Promise.all([
    client.models.Property.list(),
    client.models.IncomeEntry.list(),
    client.models.Expense.list(),
    client.models.Contact.list(),
    client.models.Note.list(),
    client.models.Settings.list(),
  ]);
  cache.properties = props.data;
  cache.income = income.data;
  cache.expenses = expenses.data;
  cache.contacts = contacts.data;
  cache.notes = notes.data;
  if(settingsList.data.length){
    cache.settings = settingsList.data[0];
  } else {
    const created = await client.models.Settings.create({ appName: 'Rent Ledger', currency: 'INR' });
    cache.settings = created.data;
  }
}

/* ================= AUTH ================= */
function renderAuth(){
  const root = document.getElementById('root');

  if(authScreen === 'confirm'){
    root.innerHTML = `
    <div class="center-screen"><div class="auth-card">
      <div class="stamp"><svg viewBox="0 0 24 24" fill="none" stroke="#B8863B" stroke-width="2" width="24" height="24"><path d="M3 10l9-7 9 7v9a2 2 0 01-2 2H5a2 2 0 01-2-2z"/></svg></div>
      <h2>Check Your Email</h2>
      <p>We sent a real verification code to ${pendingConfirmEmail}.</p>
      <div class="field"><label>Verification Code</label><input id="cf-code"></div>
      <div id="cf-error" style="color:#A8462F;font-size:12px;margin-bottom:8px;"></div>
      <button class="btn" id="cf-btn" onclick="withLoading(document.getElementById('cf-btn'), doConfirm)">Verify & Continue</button>
    </div></div>`;
    return;
  }

  if(authScreen === 'forgot-request'){
    root.innerHTML = `
    <div class="center-screen"><div class="auth-card">
      <h2>Reset Password</h2>
      <p>Enter your email — we'll send a real reset code.</p>
      <div class="field"><label>Email</label><input id="fp-email" type="email"></div>
      <div id="fp-error" style="color:#A8462F;font-size:12px;margin-bottom:8px;"></div>
      <button class="btn" id="fp-btn" onclick="withLoading(document.getElementById('fp-btn'), doForgotRequest)">Send Reset Code</button>
      <button class="link-btn" style="margin-top:14px;" onclick="setAuthScreen('signin')">Cancel</button>
    </div></div>`;
    return;
  }
  if(authScreen === 'forgot-confirm'){
    root.innerHTML = `
    <div class="center-screen"><div class="auth-card">
      <h2>Set a New Password</h2>
      <p>Enter the code sent to ${forgotEmail} and choose a new password.</p>
      <div class="field"><label>Reset Code</label><input id="fp-code"></div>
      <div class="field"><label>New Password (min 8 characters)</label><input id="fp-newpass" type="password"></div>
      <div id="fp-confirm-error" style="color:#A8462F;font-size:12px;margin-bottom:8px;"></div>
      <button class="btn" id="fp-confirm-btn" onclick="withLoading(document.getElementById('fp-confirm-btn'), doForgotConfirm)">Save New Password</button>
    </div></div>`;
    return;
  }

  if(authScreen === 'signup'){
    root.innerHTML = `
    <div class="center-screen"><div class="auth-card">
      <div class="stamp"><svg viewBox="0 0 24 24" fill="none" stroke="#B8863B" stroke-width="2" width="24" height="24"><path d="M3 10l9-7 9 7v9a2 2 0 01-2 2H5a2 2 0 01-2-2z"/></svg></div>
      <h2>Create Your Account</h2>
      <p>Each account only ever sees its own properties.</p>
      <div class="field"><label>Email</label><input id="su-email" type="email" placeholder="you@example.com"></div>
      <div class="field"><label>Password (min 8 characters, upper+lower+number+symbol)</label><input id="su-pass" type="password"></div>
      <div id="su-error" style="color:#A8462F;font-size:12px;margin-bottom:8px;"></div>
      <button class="btn" id="su-btn" onclick="withLoading(document.getElementById('su-btn'), doSignup)">Create Account</button>
      <button class="link-btn" style="margin-top:14px;" onclick="setAuthScreen('signin')">Already have an account? Sign in</button>
    </div></div>`;
    return;
  }

  root.innerHTML = `
    <div class="center-screen"><div class="auth-card">
      <div class="stamp"><svg viewBox="0 0 24 24" fill="none" stroke="#B8863B" stroke-width="2" width="24" height="24"><path d="M3 10l9-7 9 7v9a2 2 0 01-2 2H5a2 2 0 01-2-2z"/></svg></div>
      <h2>${cache.settings.appName || 'Rent Ledger'}</h2>
      <p>Sign in to your account.</p>
      <div class="field"><label>Email</label><input id="lg-email" type="email" placeholder="you@example.com"></div>
      <div class="field"><label>Password</label><input id="lg-pass" type="password"></div>
      <button class="btn" id="lg-btn" onclick="withLoading(document.getElementById('lg-btn'), doLogin)">Sign In</button>
      <div id="lg-error" style="color:#A8462F;font-size:12px;margin-top:10px;"></div>
      <button class="link-btn" style="margin-top:14px;display:block;" onclick="setAuthScreen('forgot-request')">Forgot password?</button>
      <button class="link-btn" style="margin-top:10px;" onclick="setAuthScreen('signup')">+ Create an account</button>
    </div></div>`;
}
function setAuthScreen(s){ authScreen = s; renderAuth(); }

async function doSignup(){
  const email = document.getElementById('su-email').value.trim().toLowerCase();
  const pass = document.getElementById('su-pass').value;
  const err = document.getElementById('su-error');
  try{
    await signUp({ username: email, password: pass, options: { userAttributes: { email } } });
    pendingConfirmEmail = email;
    authScreen = 'confirm';
    renderAuth();
  }catch(e){ err.textContent = e.message || 'Could not create account.'; }
}
async function doConfirm(){
  const err = document.getElementById('cf-error');
  try{
    await confirmSignUp({ username: pendingConfirmEmail, confirmationCode: document.getElementById('cf-code').value.trim() });
    authScreen = 'signin';
    renderAuth();
  }catch(e){ err.textContent = e.message || 'Could not verify code.'; }
}
async function doLogin(){
  const err = document.getElementById('lg-error');
  try{
    await signIn({
      username: document.getElementById('lg-email').value.trim().toLowerCase(),
      password: document.getElementById('lg-pass').value,
    });
    await startApp();
  }catch(e){ err.textContent = e.message || 'Could not sign in.'; }
}
async function doForgotRequest(){
  const err = document.getElementById('fp-error');
  const email = document.getElementById('fp-email').value.trim().toLowerCase();
  try{
    await resetPassword({ username: email });
    forgotEmail = email;
    authScreen = 'forgot-confirm';
    renderAuth();
  }catch(e){ err.textContent = e.message || 'Could not start password reset.'; }
}
async function doForgotConfirm(){
  const err = document.getElementById('fp-confirm-error');
  try{
    await confirmResetPassword({
      username: forgotEmail,
      confirmationCode: document.getElementById('fp-code').value.trim(),
      newPassword: document.getElementById('fp-newpass').value,
    });
    forgotEmail = null;
    authScreen = 'signin';
    renderAuth();
  }catch(e){ err.textContent = e.message || 'Could not reset password.'; }
}
async function doSignOut(){ await signOut(); currentUser = null; authScreen = 'signin'; renderAuth(); }
async function doDeleteAccount(){
  try{
    await Promise.all([
      ...cache.properties.map(p=>client.models.Property.delete({id:p.id})),
      ...cache.income.map(i=>client.models.IncomeEntry.delete({id:i.id})),
      ...cache.expenses.map(e=>client.models.Expense.delete({id:e.id})),
      ...cache.contacts.map(c=>client.models.Contact.delete({id:c.id})),
      ...cache.notes.map(n=>client.models.Note.delete({id:n.id})),
    ]);
    if(cache.settings.id) await client.models.Settings.delete({id: cache.settings.id});
    await deleteUser();
  }catch(e){ console.error(e); }
  currentUser = null;
  authScreen = 'signin';
  closeModal();
  renderAuth();
}

/* ================= SHELL ================= */
async function startApp(){
  currentUser = await getCurrentUser();
  await refreshCache();
  document.title = cache.settings.appName || 'Rent Ledger';
  const root = document.getElementById('root');
  root.innerHTML = `<div class="app"><div class="sidebar">
      <div class="brand">
        <div class="stamp"><svg viewBox="0 0 24 24" fill="none" stroke="#D9AE6B" stroke-width="2"><path d="M3 10l9-7 9 7v9a2 2 0 01-2 2H5a2 2 0 01-2-2z"/></svg></div>
        <h1>${cache.settings.appName || 'Rent Ledger'}</h1>
        <p>Property Manager</p>
      </div>
      <nav id="nav"></nav>
      <div class="sidebar-foot">
        <div class="who">👤 ${currentUser.signInDetails?.loginId || ''}</div>
        <button onclick="openSettingsModal()">SETTINGS</button>
        <button onclick="doSignOut()">SIGN OUT</button>
      </div>
    </div><main id="main"></main></div>`;
  render();
}

async function boot(){
  try{
    currentUser = await getCurrentUser();
    await startApp();
  }catch{
    authScreen = 'signin';
    renderAuth();
  }
}

function renderNav(){
  const nav = document.getElementById('nav');
  nav.innerHTML = '';
  PAGES.forEach(([key,label])=>{
    const b = document.createElement('button');
    b.className = key===page ? 'active' : '';
    b.innerHTML = ICONS[key] + '<span>'+label+'</span>';
    b.onclick = ()=>{ page = key; render(); };
    nav.appendChild(b);
  });
}

function render(){
  renderNav();
  const main = document.getElementById('main');
  if(page==='dashboard') renderDashboard(main);
  else if(page==='properties') renderProperties(main);
  else if(page==='tenants') renderTenants(main);
  else if(page==='maintenance') renderMaintenance(main);
  else if(page==='map') renderMap(main);
  else if(page==='contacts') renderContacts(main);
  else if(page==='notes') renderNotes(main);
}

/* ================= DASHBOARD ================= */
function renderDashboard(main){
  const D = cache;
  const mIncome = D.income.filter(i=>i.month===thisMonth()).reduce((s,i)=>s+Number(i.amount),0);
  const mExpense = D.expenses.filter(e=>e.date && e.date.slice(0,7)===thisMonth()).reduce((s,e)=>s+Number(e.cost),0);
  const rentRoll = D.properties.reduce((s,p)=>s+Number(p.rent||0),0);
  const occCount = D.properties.filter(p=>p.occupancy==='occupied').length;

  main.innerHTML = `
    <div class="page-head"><div><h2>Dashboard</h2><div class="sub">Overview across all properties</div></div></div>
    <div class="grid">
      <div class="stat-card"><div class="label">Properties</div><div class="value">${D.properties.length}</div></div>
      <div class="stat-card"><div class="label">Occupied</div><div class="value">${occCount}/${D.properties.length}</div></div>
      <div class="stat-card"><div class="label">Monthly Rent Roll</div><div class="value">${money(rentRoll)}</div></div>
      <div class="stat-card moss"><div class="label">Income — This Month</div><div class="value">${money(mIncome)}</div></div>
      <div class="stat-card rust"><div class="label">Expenses — This Month</div><div class="value">${money(mExpense)}</div></div>
      <div class="stat-card ${mIncome-mExpense>=0?'moss':'rust'}"><div class="label">Net — This Month</div><div class="value">${money(mIncome-mExpense)}</div></div>
    </div>
    <div class="chart-wrap">
      <h3>Income vs Expenses — Last 6 Months</h3>
      <div class="chart-box"><canvas id="mainChart"></canvas></div>
    </div>
    <div class="card">
      <h3 class="display" style="margin:0 0 14px 0;font-size:16px;">Per-Property Performance (This Month)</h3>
      ${D.properties.length===0 ? '<div class="empty">No properties yet. Add one from the Properties tab.</div>' : `
      <table><thead><tr><th>Property</th><th>Rent</th><th>Received</th><th>Spent</th><th>Net</th></tr></thead><tbody>
      ${D.properties.map(p=>{
        const inc = D.income.filter(i=>i.propertyId===p.id && i.month===thisMonth()).reduce((s,i)=>s+Number(i.amount),0);
        const exp = D.expenses.filter(e=>e.propertyId===p.id && e.date && e.date.slice(0,7)===thisMonth()).reduce((s,e)=>s+Number(e.cost),0);
        return `<tr><td>${p.name}</td><td class="mono">${money(p.rent)}</td><td class="mono">${money(inc)}</td><td class="mono">${money(exp)}</td><td class="mono" style="color:${inc-exp>=0?'#4C6B54':'#A8462F'}">${money(inc-exp)}</td></tr>`;
      }).join('')}
      </tbody></table>`}
    </div>
  `;
  drawChart();
}

function drawChart(){
  const canvas = document.getElementById('mainChart');
  if(!canvas || typeof Chart === 'undefined') return;
  const D = cache;
  const months = [];
  const d = new Date();
  for(let i=5;i>=0;i--){
    const dt = new Date(d.getFullYear(), d.getMonth()-i, 1);
    months.push(dt.toISOString().slice(0,7));
  }
  const incomeData = months.map(m=>D.income.filter(i=>i.month===m).reduce((s,i)=>s+Number(i.amount),0));
  const expenseData = months.map(m=>D.expenses.filter(e=>e.date && e.date.slice(0,7)===m).reduce((s,e)=>s+Number(e.cost),0));
  if(chartInstance) chartInstance.destroy();
  chartInstance = new Chart(canvas.getContext('2d'), {
    type:'bar',
    data:{ labels: months.map(monthLabel), datasets:[
        {label:'Income', data:incomeData, backgroundColor:'#4C6B54', borderRadius:4, maxBarThickness:34},
        {label:'Expenses', data:expenseData, backgroundColor:'#A8462F', borderRadius:4, maxBarThickness:34}
    ]},
    options:{ responsive:true, maintainAspectRatio:false,
      plugins:{legend:{position:'bottom', labels:{font:{family:'Inter'}, boxWidth:12}}},
      scales:{ y:{beginAtZero:true, grid:{color:'#D6CDB2'}, ticks:{font:{family:'IBM Plex Mono'}, callback:v=>CURRENCIES[cache.settings.currency||'INR'].symbol.trim()+v}},
        x:{grid:{display:false}, ticks:{font:{family:'IBM Plex Mono'}}} } }
  });
}

/* ================= PROPERTIES ================= */
function renderProperties(main){
  const D = cache;
  main.innerHTML = `
    <div class="page-head">
      <div><h2>Properties</h2><div class="sub">${D.properties.length} propert${D.properties.length===1?'y':'ies'} on record</div></div>
      <button class="btn" onclick="openPropertyModal()">+ Add Property</button>
    </div>
    ${D.properties.length===0 ? '<div class="empty"><div class="display">No properties yet</div>Add your first rental property to get started.</div>' : `
    <div class="prop-grid">
      ${D.properties.map(p=>{
        const contacts = propContacts(p.id);
        const tenants = p.tenants || [];
        const owners = p.owners || [];
        return `
        <div class="prop-card">
          <div class="stamp-badge ${p.occupancy==='occupied'?'occ':'vac'}">${p.occupancy==='occupied'?'OCCUPIED':'VACANT'}</div>
          <h4>${p.name}</h4>
          <div class="addr">${p.address||'No address set'}</div>
          <div class="row"><span>Monthly Rent</span><span>${money(p.rent)}</span></div>
          <div class="row"><span>Ownership</span><span>${p.ownershipType==='multiple'?owners.length+' Owners':'Single Owner'}</span></div>
          <div class="row"><span>Tenant${tenants.length>1?'s':''}</span><span>${tenants.length?tenants.map(t=>t.name).join(', '):'—'}</span></div>
          <div class="row"><span>Agreement</span><span>${p.agreementDone==='yes'?'Signed ✓':'Not signed'}</span></div>
          <div class="chips">
            ${contacts.length===0?'<span class="hint">No contacts linked yet</span>':contacts.map(c=>`<span class="chip">${c.type}: ${c.name}</span>`).join('')}
          </div>
          <div class="actions">
            <button class="btn tiny" onclick="viewProperty('${p.id}')">View</button>
            <button class="btn tiny ghost" onclick="openPropertyModal('${p.id}')">Edit</button>
            <button class="btn tiny amber" onclick="openIncomeModal('${p.id}')">Mark Rent Paid</button>
            <button class="btn tiny ghost" onclick="openContactModal('${p.id}')">+ Contact</button>
          </div>
        </div>`;
      }).join('')}
    </div>`}
  `;
}

function viewProperty(id){
  const D = cache;
  const p = D.properties.find(x=>x.id===id);
  const contacts = propContacts(id);
  const owners = p.owners || [];
  const tenants = p.tenants || [];
  const inc = D.income.filter(i=>i.propertyId===id).sort((a,b)=>b.month.localeCompare(a.month)).slice(0,4);
  const exp = D.expenses.filter(e=>e.propertyId===id).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,4);
  const modal = document.createElement('div');
  modal.className = 'overlay';
  modal.innerHTML = `
    <div class="modal">
      <h3>${p.name}</h3>
      <div class="detail-section">
        <h5>Overview</h5>
        <div class="detail-row"><span>Address</span><span>${p.address||'—'}</span></div>
        <div class="detail-row"><span>Monthly Rent</span><span class="mono">${money(p.rent)}</span></div>
        <div class="detail-row"><span>Advance / Deposit</span><span class="mono">${money(p.advanceAmount)}</span></div>
        <div class="detail-row"><span>Status</span><span>${p.occupancy==='occupied'?'Occupied':'Vacant'}</span></div>
        <div class="detail-row"><span>Occupied Since (Lease Start)</span><span class="mono">${p.occupiedSince||'—'}</span></div>
        <div class="detail-row"><span>Agreement</span><span>${p.agreementDone==='yes'?'Signed':'Not signed'}</span></div>
        <div class="detail-row"><span>Rent Due Day</span><span class="mono">Day ${p.rentDueDay||'—'}</span></div>
        <div class="detail-row"><span>Ownership</span><span>${p.ownershipType==='multiple'?owners.length+' Owners':'Single Owner'}</span></div>
      </div>
      ${p.ownershipType==='multiple' ? `
      <div class="detail-section">
        <h5>Owners</h5>
        ${owners.length===0 ? '<div class="hint">No owners added.</div>' : owners.map(o=>`
          <div class="detail-row"><span>${o.name||'Unnamed'}</span><span class="mono">${o.phone||'—'}</span></div>
        `).join('')}
      </div>` : ''}
      <div class="detail-section">
        <h5>Tenant${tenants.length>1?'s':''} on the Lease</h5>
        ${tenants.length===0 ? '<div class="hint">No tenants added.</div>' : tenants.map(t=>`
          <div class="detail-row"><span>${t.name||'Unnamed'}</span><span class="mono">${t.phone||'—'}${t.email?' · '+t.email:''}${t.mailAlertEnabled?' · alerts on':''}</span></div>
        `).join('')}
      </div>
      <div class="detail-section">
        <h5>Linked Contacts</h5>
        ${contacts.length===0?'<div class="hint">None yet.</div>':contacts.map(c=>`<div class="detail-row"><span>${c.type} — ${c.name}</span><span class="mono">${c.phone||'—'}</span></div>`).join('')}
      </div>
      <div class="detail-section">
        <h5>Recent Rent Payments</h5>
        ${inc.length===0?'<div class="hint">None recorded yet.</div>':inc.map(i=>`<div class="detail-row"><span>${monthLabel(i.month)}</span><span class="mono">${money(i.amount)} · Paid ${i.paidDate||''}</span></div>`).join('')}
      </div>
      <div class="detail-section">
        <h5>Recent Maintenance</h5>
        ${exp.length===0?'<div class="hint">None recorded yet.</div>':exp.map(e=>`<div class="detail-row"><span>${e.category}${e.description?' — '+e.description:''}</span><span class="mono">${money(e.cost)}</span></div>`).join('')}
      </div>
      <div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Close</button></div>
    </div>`;
  document.body.appendChild(modal);
}

function openPropertyModal(id){
  const D = cache;
  const p = id ? D.properties.find(x=>x.id===id) : null;
  const modal = document.createElement('div');
  modal.className = 'overlay';
  modal.innerHTML = `
    <div class="modal">
      <h3>${p?'Edit Property':'Add Property'}</h3>
      <div class="field"><label>Property Name</label><input id="f-name" value="${p?p.name:''}" placeholder="e.g. Green Villa, Unit 2B"></div>
      <div class="field-row">
        <div class="field"><label>Ownership</label>
          <select id="f-ownertype" onchange="document.getElementById('owner-section').style.display=this.value==='multiple'?'block':'none';">
            <option value="single" ${(!p||p.ownershipType!=='multiple')?'selected':''}>Single Owner</option>
            <option value="multiple" ${p&&p.ownershipType==='multiple'?'selected':''}>Multiple Owners</option>
          </select>
        </div>
      </div>
      <div id="owner-section" style="display:${p&&p.ownershipType==='multiple'?'block':'none'};">
        <div class="field"><label>Owners</label></div>
        <div id="owner-rows"></div>
        <button type="button" class="btn small ghost" style="margin-bottom:6px;" onclick="addOwnerRow()">+ Add Owner</button>
        <div class="hint" style="margin-bottom:14px;">Everyone who co-owns this property — used to label who's involved when logging expenses.</div>
      </div>
      <div class="addr-row">
        <div class="field"><label>Address</label><input id="f-address" value="${p?p.address||'':''}" placeholder="Street, city"></div>
        <button class="btn small ghost" style="margin-bottom:13px;" id="geo-btn" onclick="withLoading(document.getElementById('geo-btn'), findCoords)">📍 Find on Map</button>
      </div>
      <div id="geo-status" class="hint"></div>
      <div class="field-row">
        <div class="field"><label>Latitude</label><input id="f-lat" value="${p?p.lat||'':''}" placeholder="e.g. 9.5810"></div>
        <div class="field"><label>Longitude</label><input id="f-lng" value="${p?p.lng||'':''}" placeholder="e.g. 77.9624"></div>
      </div>
      <div class="hint" style="margin-top:-8px;margin-bottom:14px;">Can't find it automatically? Open Google Maps, long-press your property's location, then copy the two numbers shown at the bottom and paste them above.</div>
      <div class="field-row">
        <div class="field"><label>Monthly Rent</label><input id="f-rent" type="number" value="${p?p.rent||'':''}" placeholder="15000"></div>
        <div class="field"><label>Occupancy</label>
          <select id="f-occ"><option value="occupied" ${p&&p.occupancy==='occupied'?'selected':''}>Occupied</option><option value="vacant" ${p&&p.occupancy==='vacant'?'selected':''}>Vacant</option></select>
        </div>
      </div>
      <div class="field-row">
        <div class="field"><label>Advance / Security Deposit</label><input id="f-advance" type="number" value="${p?p.advanceAmount||'':''}" placeholder="e.g. 30000"></div>
        <div class="field"><label>Rent Due Day (1–31)</label><input id="f-dueday" type="number" min="1" max="31" value="${p?p.rentDueDay||'':''}"></div>
      </div>
      <div class="field-row">
        <div class="field"><label>Occupied Since (Lease Start Date)</label><input id="f-occsince" type="date" value="${p?p.occupiedSince||'':''}"></div>
        <div class="field"><label>Agreement Signed?</label>
          <select id="f-agree"><option value="no" ${p&&p.agreementDone==='no'?'selected':''}>No</option><option value="yes" ${p&&p.agreementDone==='yes'?'selected':''}>Yes</option></select>
        </div>
      </div>
      <div class="field"><label>Tenants on the Lease</label></div>
      <div id="tenant-rows"></div>
      <button type="button" class="btn small ghost" style="margin-bottom:6px;" onclick="addTenantRow()">+ Add Tenant</button>
      <div class="hint" style="margin-bottom:14px;">Add everyone signing the lease — each can have their own phone, email, and reminder setting.</div>
      <div class="field"><label>Notes</label><textarea id="f-notes">${p?p.notes||'':''}</textarea></div>
      <div class="modal-actions">
        ${p?'<button class="btn danger" onclick="deleteProperty(\''+p.id+'\')">Delete</button>':''}
        <button class="btn ghost" onclick="closeModal()">Cancel</button>
        <button class="btn" id="prop-save-btn" onclick="withLoading(document.getElementById('prop-save-btn'), ()=>saveProperty('${p?p.id:''}'))">Save</button>
      </div>
    </div>
  `;
  document.body.appendChild(modal);
  const existingTenants = (p && p.tenants && p.tenants.length) ? p.tenants : [];
  if(existingTenants.length){ existingTenants.forEach(t=>addTenantRow(t)); }
  else { addTenantRow(); }

  const existingOwners = (p && p.owners && p.owners.length) ? p.owners : [];
  if(existingOwners.length){ existingOwners.forEach(o=>addOwnerRow(o)); }
  else if(p && p.ownershipType==='multiple'){ addOwnerRow(); addOwnerRow(); }
}

function ownerRowHtml(o){
  return `<div class="tenant-row" data-oid="${o&&o.id?o.id:''}" style="border:1px solid var(--line);border-radius:8px;padding:10px;margin-bottom:8px;background:#fff;">
    <div class="field-row">
      <div class="field"><label>Owner Name</label><input class="o-name" value="${o?o.name||'':''}" placeholder="Owner name"></div>
      <div class="field"><label>Phone</label><input class="o-phone" value="${o?o.phone||'':''}"></div>
    </div>
    <button type="button" class="link-btn" onclick="this.closest('.tenant-row').remove()">Remove this owner</button>
  </div>`;
}
function addOwnerRow(o){ document.getElementById('owner-rows').insertAdjacentHTML('beforeend', ownerRowHtml(o)); }

function tenantRowHtml(t){
  return `<div class="tenant-row" data-tid="${t&&t.id?t.id:''}" style="border:1px solid var(--line);border-radius:8px;padding:12px;margin-bottom:8px;background:#fff;">
    <div class="field-row">
      <div class="field"><label>Name</label><input class="t-name" value="${t?t.name||'':''}" placeholder="Tenant name"></div>
      <div class="field"><label>Phone</label><input class="t-phone" value="${t?t.phone||'':''}"></div>
    </div>
    <div class="field-row" style="align-items:center;">
      <div class="field"><label>Email</label><input class="t-email" value="${t?t.email||'':''}"></div>
      <div class="field-check" style="margin-top:20px;"><input type="checkbox" class="t-alert" ${t&&t.mailAlertEnabled?'checked':''}><label style="margin:0;">Email alerts</label></div>
    </div>
    <button type="button" class="link-btn" onclick="this.closest('.tenant-row').remove()">Remove this tenant</button>
  </div>`;
}
function addTenantRow(t){ document.getElementById('tenant-rows').insertAdjacentHTML('beforeend', tenantRowHtml(t)); }

async function findCoords(){
  const address = document.getElementById('f-address').value.trim();
  const status = document.getElementById('geo-status');
  if(!address){ status.textContent = 'Type an address first.'; status.style.color = '#A8462F'; return; }
  status.textContent = 'Searching…'; status.style.color = '#8a8468';
  try{
    const res = await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&q=' + encodeURIComponent(address));
    const data = await res.json();
    if(data && data.length){
      document.getElementById('f-lat').value = data[0].lat;
      document.getElementById('f-lng').value = data[0].lon;
      status.textContent = '✓ Location found and filled in below.'; status.style.color = '#4C6B54';
    } else {
      status.textContent = 'Could not find that address — try adding city/state, or enter coordinates manually below.'; status.style.color = '#A8462F';
    }
  }catch(e){
    status.textContent = 'Lookup failed — check your connection, or enter coordinates manually below.'; status.style.color = '#A8462F';
  }
}

async function saveProperty(id){
  const data = {
    name: document.getElementById('f-name').value.trim() || 'Untitled Property',
    address: document.getElementById('f-address').value.trim(),
    lat: document.getElementById('f-lat').value.trim(),
    lng: document.getElementById('f-lng').value.trim(),
    rent: Number(document.getElementById('f-rent').value) || 0,
    advanceAmount: Number(document.getElementById('f-advance').value) || 0,
    occupancy: document.getElementById('f-occ').value,
    occupiedSince: document.getElementById('f-occsince').value,
    agreementDone: document.getElementById('f-agree').value,
    rentDueDay: Number(document.getElementById('f-dueday').value) || 1,
    notes: document.getElementById('f-notes').value.trim(),
    tenants: Array.from(document.querySelectorAll('#tenant-rows .tenant-row')).map(row=>({
      id: row.dataset.tid || uid(),
      name: row.querySelector('.t-name').value.trim(),
      phone: row.querySelector('.t-phone').value.trim(),
      email: row.querySelector('.t-email').value.trim(),
      mailAlertEnabled: row.querySelector('.t-alert').checked
    })).filter(t=>t.name || t.phone || t.email),
    ownershipType: document.getElementById('f-ownertype').value,
    owners: document.getElementById('f-ownertype').value==='multiple'
      ? Array.from(document.querySelectorAll('#owner-rows .tenant-row')).map(row=>({
          id: row.dataset.oid || uid(),
          name: row.querySelector('.o-name').value.trim(),
          phone: row.querySelector('.o-phone').value.trim()
        })).filter(o=>o.name || o.phone)
      : []
  };
  if(id){ await client.models.Property.update({ id, ...data }); }
  else { await client.models.Property.create(data); }
  await refreshCache();
  closeModal();
  render();
}

async function deleteProperty(id){
  await Promise.all([
    ...cache.income.filter(i=>i.propertyId===id).map(i=>client.models.IncomeEntry.delete({id:i.id})),
    ...cache.expenses.filter(e=>e.propertyId===id).map(e=>client.models.Expense.delete({id:e.id})),
    ...cache.contacts.filter(c=>c.propertyId===id).map(c=>client.models.Contact.delete({id:c.id})),
  ]);
  await client.models.Property.delete({ id });
  await refreshCache();
  closeModal();
  render();
}

function openIncomeModal(propertyId){
  const p = cache.properties.find(x=>x.id===propertyId);
  const modal = document.createElement('div');
  modal.className = 'overlay';
  modal.innerHTML = `
    <div class="modal">
      <h3>Mark Rent Paid — ${p.name}</h3>
      <div class="field"><label>Month</label><input id="i-month" type="month" value="${thisMonth()}"></div>
      <div class="field"><label>Amount</label><input id="i-amount" type="number" value="${p.rent||''}"></div>
      <div class="hint" style="margin-bottom:14px;">Today's date (${today()}) will be recorded as the payment date automatically.</div>
      <div class="modal-actions">
        <button class="btn ghost" onclick="closeModal()">Cancel</button>
        <button class="btn amber" id="income-save-btn" onclick="withLoading(document.getElementById('income-save-btn'), ()=>saveIncome('${propertyId}'))">✓ Mark as Paid</button>
      </div>
    </div>`;
  document.body.appendChild(modal);
}

async function saveIncome(propertyId){
  const month = document.getElementById('i-month').value || thisMonth();
  const amount = Number(document.getElementById('i-amount').value) || 0;
  const existing = cache.income.find(i=>i.propertyId===propertyId && i.month===month);
  if(existing){ await client.models.IncomeEntry.update({ id: existing.id, amount, paidDate: today() }); }
  else { await client.models.IncomeEntry.create({ propertyId, month, amount, paidDate: today() }); }
  await refreshCache();
  closeModal();
  render();
}

/* ================= SETTINGS ================= */
function openSettingsModal(){
  const opts = Object.keys(CURRENCIES).map(code=>`<option value="${code}" ${(cache.settings.currency||'INR')===code?'selected':''}>${CURRENCIES[code].label}</option>`).join('');
  const modal = document.createElement('div');
  modal.className = 'overlay';
  modal.innerHTML = `
    <div class="modal" style="max-width:420px;">
      <h3>Settings</h3>
      <div class="field"><label>App Name</label><input id="set-appname" value="${cache.settings.appName||'Rent Ledger'}" placeholder="e.g. Sures Properties"></div>
      <div class="field"><label>Currency</label><select id="set-currency">${opts}</select></div>
      <div class="hint" style="margin-bottom:14px;">Currency changes how amounts are displayed everywhere — your stored numbers don't change.</div>
      <div class="detail-section">
        <h5>Account</h5>
        <div class="detail-row"><span>Email</span><span class="mono">${currentUser.signInDetails?.loginId||''}</span></div>
      </div>
      <div class="detail-section">
        <h5>Danger Zone</h5>
        <button class="link-btn" style="color:#A8462F;" onclick="document.getElementById('del-acc-confirm').style.display='block';">Delete this account</button>
        <div id="del-acc-confirm" style="display:none;" class="reset-box">
          <div class="msg">This permanently deletes this login <b>and all its properties, tenants, and records</b>. There's no undo.</div>
          <div class="btnrow">
            <button class="btn small danger" style="width:auto;" onclick="doDeleteAccount()">Yes, delete everything</button>
            <button class="btn small ghost" style="width:auto;" onclick="document.getElementById('del-acc-confirm').style.display='none';">Cancel</button>
          </div>
        </div>
      </div>
      <div class="modal-actions">
        <button class="btn ghost" onclick="closeModal()">Cancel</button>
        <button class="btn" id="set-save-btn" onclick="withLoading(document.getElementById('set-save-btn'), saveSettings)">Save</button>
      </div>
    </div>`;
  document.body.appendChild(modal);
}

async function saveSettings(){
  const appName = document.getElementById('set-appname').value.trim() || 'Rent Ledger';
  const currency = document.getElementById('set-currency').value;
  await client.models.Settings.update({ id: cache.settings.id, appName, currency });
  await refreshCache();
  closeModal();
  await startApp();
}

/* ================= TENANTS ================= */
function renderTenants(main){
  const D = cache;
  const now = new Date();
  main.innerHTML = `
    <div class="page-head"><div><h2>Tenants</h2><div class="sub">Rent status for ${monthLabel(thisMonth())}</div></div></div>
    ${D.properties.length===0 ? '<div class="empty">No properties yet.</div>' : `
    <div class="card">
    <table><thead><tr><th>Tenant</th><th>Property</th><th>Rent Due</th><th>Status</th><th>Remind</th></tr></thead><tbody>
    ${D.properties.map(p=>{
      if(p.occupancy!=='occupied') return `<tr><td colspan="5" style="color:#a09a80;">${p.name} — vacant</td></tr>`;
      const paid = D.income.some(i=>i.propertyId===p.id && i.month===thisMonth());
      const dueDay = Number(p.rentDueDay)||1;
      const diff = dueDay - now.getDate();
      let statusTag;
      if(paid) statusTag = '<span class="tag ok">PAID</span>';
      else if(diff < 0) statusTag = `<span class="tag late">${Math.abs(diff)} DAY${Math.abs(diff)===1?'':'S'} OVERDUE</span>`;
      else if(diff <= 3) statusTag = `<span class="tag soon">DUE IN ${diff} DAY${diff===1?'':'S'}</span>`;
      else statusTag = '<span class="tag neutral">PENDING</span>';
      const tenants = (p.tenants && p.tenants.length) ? p.tenants : [{name:'—'}];
      return tenants.map(t=>{
        const alertsOn = t.mailAlertEnabled && t.email;
        const mailto = alertsOn ? `mailto:${t.email}?subject=${encodeURIComponent('Rent reminder — '+p.name)}&body=${encodeURIComponent('Hi '+(t.name||'')+',\n\nThis is a reminder that rent of '+money(p.rent)+' for '+p.name+' is due on day '+dueDay+' of this month.\n\nThanks!')}` : null;
        return `<tr>
          <td>${t.name||'—'}</td>
          <td>${p.name}</td>
          <td class="mono">Day ${dueDay}</td>
          <td>${statusTag}</td>
          <td>${paid?'—':(mailto?`<a class="btn tiny amber" href="${mailto}" style="text-decoration:none;">✉ Email</a>`:'<span class="hint">Turn on alerts for this tenant</span>')}</td>
        </tr>`;
      }).join('');
    }).join('')}
    </tbody></table>
    </div>
    <div class="hint" style="margin-top:8px;">"✉ Email" opens a reminder in your own mail app. Fully automatic scheduled emails (sent without clicking) need Amazon SES + a scheduled job — ask if you want that added.</div>`}
  `;
}

/* ================= MAINTENANCE ================= */
function renderMaintenance(main){
  const D = cache;
  let sorted = [...D.expenses].sort((a,b)=>(b.date||'').localeCompare(a.date||''));
  if(maintenanceFilterId !== 'all') sorted = sorted.filter(e=>e.propertyId===maintenanceFilterId);
  const filterOpts = `<option value="all">All properties</option>` + D.properties.map(p=>`<option value="${p.id}" ${maintenanceFilterId===p.id?'selected':''}>${p.name}${p.address?' — '+p.address:''}</option>`).join('');
  main.innerHTML = `
    <div class="page-head">
      <div><h2>Maintenance & Expenses</h2><div class="sub">${D.expenses.length} entries logged</div></div>
      <button class="btn" onclick="openExpenseModal()" ${D.properties.length===0?'disabled':''}>+ Log Expense</button>
    </div>
    ${D.properties.length===0 ? '<div class="empty">Add a property first before logging expenses.</div>' : `
    <div class="field" style="max-width:320px;margin-bottom:16px;"><label>View by property</label><select onchange="maintenanceFilterId=this.value;render();">${filterOpts}</select></div>
    ${sorted.length===0 ? '<div class="empty">No maintenance or expenses for this view.</div>' : `
    <div class="card">
    <table><thead><tr><th>Date</th><th>Property</th><th>Category</th><th>Description</th><th>Cost</th><th>Owner</th><th>Contact</th></tr></thead><tbody>
    ${sorted.map(e=>{
      const c = e.contactId ? D.contacts.find(x=>x.id===e.contactId) : null;
      const prop = D.properties.find(x=>x.id===e.propertyId);
      const owner = (prop && prop.owners) ? prop.owners.find(o=>o.id===e.ownerId) : null;
      return `<tr>
      <td class="mono">${e.date||'—'}</td>
      <td>${propName(e.propertyId)}</td>
      <td><span class="tag neutral">${e.category}</span></td>
      <td>${e.description||'—'}</td>
      <td class="mono">${money(e.cost)}</td>
      <td>${owner?owner.name:'—'}</td>
      <td class="mono">${c?c.name+(c.phone?' · '+c.phone:''):'—'}</td>
    </tr>`;}).join('')}
    </tbody></table>
    </div>`}`}
  `;
}

function openExpenseModal(){
  const opts = cache.properties.map(p=>`<option value="${p.id}">${p.name}${p.address?' — '+p.address:''}</option>`).join('');
  const modal = document.createElement('div');
  modal.className = 'overlay';
  modal.innerHTML = `
    <div class="modal">
      <h3>Log Maintenance / Expense</h3>
      <div class="field"><label>Property</label><select id="e-prop" onchange="refreshContactOptions()">${opts}</select></div>
      <div class="field-row">
        <div class="field"><label>Category</label>
          <select id="e-cat" onchange="document.getElementById('e-cat-other').style.display=this.value==='Other'?'block':'none';">
            <option>Repair</option><option>Insurance</option><option>Property Tax</option><option>Utilities</option><option>Cleaning</option><option>Pest Control</option><option>Other</option>
          </select>
        </div>
        <div class="field"><label>Cost</label><input id="e-cost" type="number" placeholder="0"></div>
      </div>
      <div class="field" id="e-cat-other" style="display:none;"><label>Type the category</label><input id="e-cat-custom" placeholder="e.g. Pipe replacement"></div>
      <div class="field"><label>Description <span style="color:#A8462F;">(always fill this in — this is how you'll track who fixed what later)</span></label><input id="e-desc" placeholder="e.g. Fixed kitchen tap leak"></div>
      <div class="field"><label>Date</label><input id="e-date" type="date" value="${today()}"></div>
      <div class="field" id="e-owner-field" style="display:none;"><label>Owner (which co-owner is this for/reported by)</label><select id="e-owner"></select></div>
      <div class="field"><label>Contact who did the work</label><select id="e-contact"></select></div>
      <div class="hint" style="margin-bottom:10px;">Don't see them? Add them from the Contacts page first — then they'll show up here.</div>
      <div class="modal-actions">
        <button class="btn ghost" onclick="closeModal()">Cancel</button>
        <button class="btn" id="exp-save-btn" onclick="withLoading(document.getElementById('exp-save-btn'), saveExpense)">Save</button>
      </div>
    </div>`;
  document.body.appendChild(modal);
  refreshContactOptions();
}

function refreshContactOptions(){
  const propId = document.getElementById('e-prop').value;
  const sel = document.getElementById('e-contact');
  const contacts = propContacts(propId);
  sel.innerHTML = '<option value="">— None —</option>' + contacts.map(c=>`<option value="${c.id}">${c.type} — ${c.name}${c.phone?' ('+c.phone+')':''}</option>`).join('');

  const prop = cache.properties.find(p=>p.id===propId);
  const ownerField = document.getElementById('e-owner-field');
  const ownerSel = document.getElementById('e-owner');
  const owners = (prop && prop.owners) ? prop.owners : [];
  if(prop && prop.ownershipType==='multiple' && owners.length){
    ownerField.style.display = 'block';
    ownerSel.innerHTML = '<option value="">— Not specified —</option>' + owners.map(o=>`<option value="${o.id}">${o.name}</option>`).join('');
  } else {
    ownerField.style.display = 'none';
    ownerSel.innerHTML = '';
  }
}

async function saveExpense(){
  const cat = document.getElementById('e-cat').value;
  const category = cat==='Other' ? (document.getElementById('e-cat-custom').value.trim() || 'Other') : cat;
  await client.models.Expense.create({
    propertyId: document.getElementById('e-prop').value,
    category,
    cost: Number(document.getElementById('e-cost').value) || 0,
    description: document.getElementById('e-desc').value.trim(),
    date: document.getElementById('e-date').value,
    ownerId: document.getElementById('e-owner') ? (document.getElementById('e-owner').value || null) : null,
    contactId: document.getElementById('e-contact').value || null
  });
  await refreshCache();
  closeModal();
  render();
}

/* ================= MAP ================= */
function renderMap(main){
  const D = cache;
  main.innerHTML = `
    <div class="page-head"><div><h2>Property Map</h2><div class="sub">Pins are set when you enter or find coordinates while adding a property</div></div></div>
    <div id="map"></div>
  `;
  const withCoords = D.properties.filter(p=>p.lat && p.lng);
  const center = withCoords.length ? [Number(withCoords[0].lat), Number(withCoords[0].lng)] : [22.9734, 78.6569];
  setTimeout(()=>{
    try{
      if(typeof L === 'undefined') throw new Error('Leaflet not loaded');
      if(leafletMap){ leafletMap.remove(); leafletMap = null; }
      leafletMap = L.map('map').setView(center, withCoords.length ? 11 : 5);
      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '&copy; OpenStreetMap contributors' }).addTo(leafletMap);
      if(withCoords.length===0){
        L.popup().setLatLng(center).setContent('No pins yet — edit a property and add latitude/longitude.').openOn(leafletMap);
      }
      withCoords.forEach(p=>{
        L.marker([Number(p.lat), Number(p.lng)]).addTo(leafletMap)
          .bindPopup(`<b>${p.name}</b><br>${p.address||''}<br>Rent: ${money(p.rent)}<br>${p.occupancy==='occupied'?'Occupied':'Vacant'}`);
      });
    }catch(e){
      document.getElementById('map').innerHTML = '<div class="empty">Map could not load. Check your internet connection and refresh.</div>';
    }
  }, 50);
}

/* ================= CONTACTS ================= */
function renderContacts(main){
  const D = cache;
  main.innerHTML = `
    <div class="page-head">
      <div><h2>Contacts</h2><div class="sub">Plumbers, electricians and other vendors, organized by property</div></div>
      <button class="btn" onclick="openContactModal()" ${D.properties.length===0?'disabled':''}>+ Add Contact</button>
    </div>
    ${D.properties.length===0 ? '<div class="empty">Add a property first, then add contacts for it.</div>' :
    D.contacts.length===0 ? '<div class="empty">No contacts yet. Add your plumber, electrician, etc.</div>' : `
    <div class="prop-grid">
    ${D.contacts.map(c=>`
      <div class="prop-card">
        <h4 style="padding-right:0;">${c.name}</h4>
        <div class="addr">${c.type} · ${propName(c.propertyId)}</div>
        <div class="row"><span>Phone</span><span>${c.phone||'—'}</span></div>
        <div class="row"><span>Notes</span><span>${c.notes||'—'}</span></div>
        <div class="actions">
          <button class="btn tiny ghost" onclick="openContactModal('${c.propertyId}','${c.id}')">Edit</button>
          <button class="btn tiny danger" onclick="deleteContact('${c.id}')">Remove</button>
        </div>
      </div>
    `).join('')}
    </div>`}
  `;
}

function openContactModal(propertyId, contactId){
  const D = cache;
  const c = contactId ? D.contacts.find(x=>x.id===contactId) : null;
  if(c) propertyId = c.propertyId;
  const opts = D.properties.map(p=>`<option value="${p.id}" ${p.id===propertyId?'selected':''}>${p.name}${p.address?' — '+p.address:''}</option>`).join('');
  const isCustomType = c && !CONTACT_TYPES.includes(c.type);
  const typeOpts = CONTACT_TYPES.map(t=>`<option ${c&&c.type===t?'selected':''}>${t}</option>`).join('');
  const modal = document.createElement('div');
  modal.className = 'overlay';
  modal.innerHTML = `
    <div class="modal">
      <h3>${c?'Edit Contact':'Add Contact'}</h3>
      <div class="field"><label>Property</label><select id="c-prop">${opts}</select></div>
      <div class="field-row">
        <div class="field"><label>Type / Occupation</label>
          <select id="c-type" onchange="document.getElementById('c-type-other').style.display=this.value==='Other'?'block':'none';">
            ${typeOpts}<option value="Other" ${isCustomType?'selected':''}>Other</option>
          </select>
        </div>
        <div class="field"><label>Name</label><input id="c-name" value="${c?c.name:''}" placeholder="e.g. Suresh"></div>
      </div>
      <div class="field" id="c-type-other" style="display:${isCustomType?'block':'none'};"><label>Type the occupation</label><input id="c-type-custom" value="${isCustomType?c.type:''}" placeholder="e.g. Locksmith"></div>
      <div class="field"><label>Phone</label><input id="c-phone" value="${c?c.phone||'':''}" placeholder="e.g. 98765 43210"></div>
      <div class="field"><label>Notes</label><input id="c-notes" value="${c?c.notes||'':''}" placeholder="optional"></div>
      <div class="modal-actions">
        ${c?'<button class="btn danger" onclick="deleteContact(\''+c.id+'\')">Delete</button>':''}
        <button class="btn ghost" onclick="closeModal()">Cancel</button>
        <button class="btn" id="contact-save-btn" onclick="withLoading(document.getElementById('contact-save-btn'), ()=>saveContact('${c?c.id:''}'))">Save</button>
      </div>
    </div>`;
  document.body.appendChild(modal);
}

async function saveContact(id){
  const typeVal = document.getElementById('c-type').value;
  const type = typeVal==='Other' ? (document.getElementById('c-type-custom').value.trim() || 'Other') : typeVal;
  const data = {
    propertyId: document.getElementById('c-prop').value,
    type,
    name: document.getElementById('c-name').value.trim() || 'Unnamed',
    phone: document.getElementById('c-phone').value.trim(),
    notes: document.getElementById('c-notes').value.trim()
  };
  if(id){ await client.models.Contact.update({ id, ...data }); }
  else { await client.models.Contact.create(data); }
  await refreshCache();
  closeModal();
  render();
}

async function deleteContact(id){
  await client.models.Contact.delete({ id });
  await refreshCache();
  closeModal();
  render();
}

/* ================= NOTES / UPCOMING PLANS ================= */
function renderNotes(main){
  const D = cache;
  const sorted = [...D.notes].sort((a,b)=>(a.done===b.done?0:a.done?1:-1));
  main.innerHTML = `
    <div class="page-head">
      <div><h2>Upcoming Plans</h2><div class="sub">Reminders and to-dos that don't belong to one property — renewals, planned repairs, ideas</div></div>
    </div>
    <div class="card">
      <div class="field-row" style="align-items:flex-end;">
        <div class="field" style="flex:2;"><label>What's coming up?</label><input id="note-text" placeholder="e.g. Renew Green Villa agreement in August"></div>
        <div class="field"><label>Target Date</label><input id="note-date" type="date"></div>
        <button class="btn" id="note-add-btn" style="margin-bottom:13px;" onclick="withLoading(document.getElementById('note-add-btn'), addNote)">Add</button>
      </div>
    </div>
    <div class="card">
      ${sorted.length===0?'<div class="empty">No upcoming plans yet.</div>':sorted.map(n=>`
        <div class="note-item">
          <input type="checkbox" ${n.done?'checked':''} onchange="toggleNote('${n.id}')">
          <div class="txt ${n.done?'done':''}">${n.text}${n.date?` <span class="date">· ${n.date}</span>`:''}</div>
          <button class="btn tiny danger" onclick="deleteNote('${n.id}')">Remove</button>
        </div>
      `).join('')}
    </div>
  `;
}

async function addNote(){
  const text = document.getElementById('note-text').value.trim();
  if(!text) return;
  await client.models.Note.create({ text, date: document.getElementById('note-date').value, done:false });
  await refreshCache();
  render();
}
async function toggleNote(id){
  const n = cache.notes.find(x=>x.id===id);
  await client.models.Note.update({ id, done: !n.done });
  await refreshCache();
  render();
}
async function deleteNote(id){
  await client.models.Note.delete({ id });
  await refreshCache();
  render();
}

/* ================= EXPOSE HANDLERS FOR INLINE onclick MARKUP ================= */
Object.assign(window, {
  withLoading, setAuthScreen, doSignup, doConfirm, doLogin, doForgotRequest, doForgotConfirm,
  doSignOut, doDeleteAccount, openSettingsModal, saveSettings, closeModal, render,
  viewProperty, openPropertyModal, addOwnerRow, addTenantRow, findCoords, saveProperty,
  deleteProperty, openIncomeModal, saveIncome, openExpenseModal, refreshContactOptions,
  saveExpense, openContactModal, saveContact, deleteContact, addNote, toggleNote, deleteNote,
});
Object.defineProperty(window, 'maintenanceFilterId', {
  get(){ return maintenanceFilterId; },
  set(v){ maintenanceFilterId = v; }
});

/* ================= INIT ================= */
boot();
